language: java
deploy:
  provider: heroku
  api_key:
    secure: ekF4rXQd+1IuV3vWPDdVy2WN3s62ZSl4dEPkpu/5L64uHGRWtut06UojPuB6005yyX94nLFVjvUZFXtAMLU3D845sfcQLl+VEJFMdhfhz2+7PIhmrWlTWk533GXpGBZfavtfgvf/EbjatMAWHSYgEE28efOgmzO/Z6tUZY1kCYGZ138mDvXCRBBosCu7Bg8+1anaEZ8L9jDIYX+sH/9O34JpthDuPiFHg75uuhqU0uVJWWC/VQjP/Z4vo2uCHElviJb5e7m3vpVP1h67LBbFhyx80jg3B3aEklzQcpxR+Ok1wkB4bP/l99zoWJRrjhrH3C1yEAcBjudMBpm5vN6LyaBSasnrrbB1lE9KutYAulgLb6jNGbN1uQBJuWHvcrSoZGRs+GrysZWO0S7/0jGXPjvagr30g7ku2Q7mdQdpREXbLOtbuA3rgK7GKmeSY2TVmq9ZtEdUQVyjovJArzN8awknfuj6ecDz4qoZCOqDAE1TVlgRAWnwi7RQNTsp8L5q9+HQSlqf+Mv7xoufg38+wPgLJbHy57X+WXIsh2rKNiHcmGOdAzl7aO4IVANEMPq4JXMN9Dk6dQfNJrTIBCWm2N6zqRZRAWM4Zhx5kAqeFX0kH4AiPQeX1xs5r9iH5BX6WmwxIfk6gcKSNON6KIDYncFI0S1Kso//+1vZCodh34o=
app: funfactory
